name: Keep Render API Alive

on:
  schedule:
    - cron: "*/10 * * * *" 
  workflow_dispatch:

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render API
        run: curl -X GET "https://humble-superhero-app.onrender.com/api/v1/superheroes"
